services:
  frontend:
    restart: on-failure
    build: ./frontend
    hostname: frontend
    ports:
      - "3000:3000"
    networks:
      - cs3219

  user-service:
    restart: on-failure
    build: ./user-service
    hostname: user-service
    ports:
      - "8000:8000"
    networks:
      - cs3219

  matching-service:
    restart: on-failure
    build: ./matching-service
    hostname: matching-service
    ports:
      - "8001:8001"
    networks:
      - cs3219
      
  question-service:
    restart: on-failure
    build: ./question-service
    hostname: question-service
    ports:
      - "8080:8080"
    networks:
      - cs3219
      
  communication-service:
    restart: on-failure
    build: ./communication-service
    hostname: communication-service
    ports:
      - "8081:8081"
    networks:
      - cs3219

  collab-service:
    restart: on-failure
    build: ./collab-service
    hostname: collab-service
    ports:
      - "1234:1234"
    networks:
      - cs3219

networks:
    cs3219:
